name: b_safe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.21.0
  firebase_auth: 3.11.0
  google_fonts: ^3.0.1
  numeric_keyboard: ^1.1.0
  dartz: ^0.10.1
  pin_code_fields: 7.4.0
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.2.1
  permission_handler: ^10.0.2
  geolocator: ^9.0.2

dev_dependencies: 
  flutter_lints: 2.0.1
  very_good_analysis: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

