name: b_safe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-49.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.21.0
  firebase_auth: 3.6.4
  google_fonts: ^3.0.1
  flutter: 
    sdk: flutter
  dartz: ^0.10.1

dev_dependencies: 
  flutter_lints: 2.0.1
  very_good_analysis: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

