// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUJZWqrNHCOQl9l3s15G7Wfryz-afdhzQ',
    appId: '1:964497007551:web:0ba0f02edfe63c0b63770a',
    messagingSenderId: '964497007551',
    projectId: 'bsaafe',
    authDomain: 'bsaafe.firebaseapp.com',
    storageBucket: 'bsaafe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuq2g4D_DkJL_YMs7J_fXuYv1qL4Xw7c',
    appId: '1:964497007551:android:a8ee74125d83db7b63770a',
    messagingSenderId: '964497007551',
    projectId: 'bsaafe',
    storageBucket: 'bsaafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAziPDkU8zceBC9wsxkL0GCvbU7llSzJks',
    appId: '1:964497007551:ios:e09fcae19a58917e63770a',
    messagingSenderId: '964497007551',
    projectId: 'bsaafe',
    storageBucket: 'bsaafe.appspot.com',
    iosClientId: '964497007551-4oii8ab2ie7n8apl6jd8srod8o8lft2q.apps.googleusercontent.com',
    iosBundleId: 'com.proj.bsafe.bSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAziPDkU8zceBC9wsxkL0GCvbU7llSzJks',
    appId: '1:964497007551:ios:e09fcae19a58917e63770a',
    messagingSenderId: '964497007551',
    projectId: 'bsaafe',
    storageBucket: 'bsaafe.appspot.com',
    iosClientId: '964497007551-4oii8ab2ie7n8apl6jd8srod8o8lft2q.apps.googleusercontent.com',
    iosBundleId: 'com.proj.bsafe.bSafe',
  );
}
